### PR TITLE
Simplify the activity to have one step

### LINKED ISSUE #15: Instructions for version 1 seem to be confusing some people
I'm starting to see a pattern where final answers for this challenge look like the code below. Note that I replaced real solutions with calls to a fake method named `example_method()` to hopefully remove spoilers from this issue.

```ruby
# Version 1
def detect_anagram(word1, word2)
  canonical(word1) == canonical(word2)
  example_method(word1) == example_method(word2)
end

# Version 2
def canonical(word) 
  example_method(word)
end

# ...
```

I hope it's clear, but what seems to be happening is that people leave their version 1 solutions in when they complete version 2. Should we try to make it more clear that you only need `canonical(word1) == canonical(word2)` in the version 1 method when you're submitting? If so, how?

### PR DESCRIPTION
**Pull request by nicolasmccurdy**
Fixes #15.

CC @J3RN @degoeym

### CODE REVIEW

**Comment by nicolasmccurdy** [comment]
Should I lower the time limit? I just noticed that most beginner activities don't have time limits, so maybe they should be removed.

**Comment by J3RN** [comment]
I'd probably move for removing them for consistency or adding them everywhere, but I've largely been ignoring them.

**Comment by nicolasmccurdy** [comment]
@jaybobo What do you think?

**Comment by jaybobo** [comment]
Let's not put time limits on beginner drills to reduce the potential for anxiety.

**Comment by nicolasmccurdy** [comment]
I agree, I don't think they're necessary (especially since there isn't a reason to make this competitive or restrictive).

**Comment by nicolasmccurdy** [comment]
I removed them from beginner drills.

**Comment by jaybobo** [comment]
:+1:

**Comment by nicolasmccurdy** [comment]
Anyway, is anyone for or against merging this?

**Comment by J3RN** [comment]
I have no objections. Merge away!

**Pull request merged**
